import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

import LoginForm from '@/components/LoginForm'
import NavBar from '@/components/NavBar'
import SearchFilterBar from '@/components/SearchFilterBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Outreach circle app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       {/* <LoginForm/> */}
       {/* <NavBar/> */}
       <SearchFilterBar/>
      </main>
    </>
  )
}
